### ISSUE TITLE
Made a mistake on my tool, counter starts fr0m 0

### ISSUE THREAD

**Issue by Silver-Golden** [td512/Humble-Trove-Downloader#1]
I was basing it off of https://imgur.com/Nlq0oPB.png where tehre was no chunk 0 (some systems do start at 1, like matlab)

Problem is this cuts off the first 20 items

https://github.com/td512/Humble-Trove-Downloader/blob/54d71d04ef0967b637f19b7dbc3ccebe8fc80995/Humble%20Trove%20Downloader/Form1.vb#L10

**Comment by td512** [comment]
Fixed. CDN purge could take a couple seconds.
