### ISSUE TITLE
Cannot login with Humble

### ISSUE THREAD

**Issue by OshDubh** [td512/Humble-Trove-Downloader#3]
I enter my credentials, but nothing happens when I click login.

**Comment by td512** [comment]
This is a known issue. Unfortunately I don't currently have the time to be able to fix this. Humble changed how their site login works. Part of this also depends on getting a HTTPONLY cookie from IE. If you've got any suggestions, feel free

**Comment by td512** [comment]
@OshDubh I've fixed this in the latest release. I'll be publishing a new release sometime tonight

**Comment by OshDubh** [comment]
Thanks @td512 Great job
