### ISSUE TITLE
Error 400 when I boot up the app

### ISSUE THREAD

**Issue by Booyahhayoob** [td512/Humble-Trove-Downloader#5]
> See the end of this message for details on invoking 
> just-in-time (JIT) debugging instead of this dialog box.
> 
> ************** Exception Text **************
> System.Net.WebException: The remote server returned an error: (400) Bad Request.
>    at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
>    at System.Net.WebClient.DownloadString(Uri address)
>    at Humble_Trove_Downloader.Form1.Form1_VisibleChanged(Object sender, EventArgs e)
>    at System.Windows.Forms.Control.OnVisibleChanged(EventArgs e)
>    at System.Windows.Forms.Form.OnVisibleChanged(EventArgs e)
>    at System.Windows.Forms.Control.WmShowWindow(Message& m)
>    at System.Windows.Forms.Control.WndProc(Message& m)
>    at System.Windows.Forms.Form.WmShowWindow(Message& m)
>    at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
> 
> 
> ************** Loaded Assemblies **************
> mscorlib
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.8.4180.0 built by: NET48REL1LAST_B
>     CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
> ----------------------------------------
> Humble Trove Downloader
>     Assembly Version: 1.0.0.0
>     Win32 Version: 1.0.0.0
>     CodeBase: file:///C:/Program%20Files%20(x86)/M6%20Securities/Humble%20Trove%20Downloader/Humble%20Trove%20Downloader.exe
> ----------------------------------------
> Microsoft.VisualBasic
>     Assembly Version: 10.0.0.0
>     Win32 Version: 14.8.3752.0 built by: NET48REL1
>     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Microsoft.VisualBasic/v4.0_10.0.0.0__b03f5f7f11d50a3a/Microsoft.VisualBasic.dll
> ----------------------------------------
> System
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.8.4001.0 built by: NET48REL1LAST_C
>     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
> ----------------------------------------
> System.Core
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.8.4180.0 built by: NET48REL1LAST_B
>     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
> ----------------------------------------
> System.Windows.Forms
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.8.4150.0 built by: NET48REL1LAST_C
>     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
> ----------------------------------------
> System.Drawing
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.8.3752.0 built by: NET48REL1
>     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
> ----------------------------------------
> System.Configuration
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.8.4190.0 built by: NET48REL1LAST_B
>     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
> ----------------------------------------
> System.Xml
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.8.3752.0 built by: NET48REL1
>     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
> ----------------------------------------
> System.Runtime.Remoting
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.8.3752.0 built by: NET48REL1
>     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Remoting/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Remoting.dll
> ----------------------------------------
> Syroot.KnownFolders
>     Assembly Version: 1.2.1.0
>     Win32 Version: 1.2.1.0
>     CodeBase: file:///C:/Program%20Files%20(x86)/M6%20Securities/Humble%20Trove%20Downloader/Syroot.KnownFolders.DLL
> ----------------------------------------
> Newtonsoft.Json
>     Assembly Version: 6.0.0.0
>     Win32 Version: 6.0.8.18111
>     CodeBase: file:///C:/Program%20Files%20(x86)/M6%20Securities/Humble%20Trove%20Downloader/Newtonsoft.Json.DLL
> ----------------------------------------
> 
> ************** JIT Debugging **************
> To enable just-in-time (JIT) debugging, the .config file for this
> application or computer (machine.config) must have the
> jitDebugging value set in the system.windows.forms section.
> The application must also be compiled with debugging
> enabled.
> 
> For example:
> 
> <configuration>
>     <system.windows.forms jitDebugging="true" />
> </configuration>
> 
> When JIT debugging is enabled, any unhandled exception
> will be sent to the JIT debugger registered on the computer
> rather than be handled by this dialog box.

**Comment by td512** [comment]
I'll take a look at this when I get home - I think I know what's happening though

**Comment by td512** [comment]
found the issue, I've seeded test binaries to the people who test this for me, it'll be fixed in 1.7.1

**Comment by td512** [comment]
Fixed! [Here you go](https://ltscdn.m6.nz/humble/trove-downloader.exe?version=1.7.1&utm_source=htd-github)
