### ISSUE TITLE
Session variable not pulling correctly and download all goes into Windows folder

### ISSUE THREAD

**Issue by migasj** [td512/Humble-Trove-Downloader#7]
The session variable _simpleauth_sess has a space before it making it not match correctly.
All files are downloading into the Windows directly when download all is selected.

**Comment by migasj** [comment]
At a second look I see that only linux was set to download to the windows directory, not mac. Regardless, my pull request fixes this issue.

**Comment by td512** [comment]
> The session variable _simpleauth_sess has a space before it making it not match correctly.

Will this match if there's a space when splitting cookies?

**Comment by migasj** [comment]
It wouldn't which was what was needed in my experience but I understand now you needed that space for it to work on your machine. I've updated it with a Trim so that it will remove the space before doing the comparison so that it will work, space or not. Let me know what you think.

**Comment by td512** [comment]
LGTM, did you see the other things I'd like to implement at some point?

**Comment by migasj** [comment]
I think I must be blind because I can't find them. Where is the feature list?

**Comment by td512** [comment]
[_cough_](https://github.com/td512/Humble-Trove-Downloader/pull/8#issuecomment-695156352)

**Comment by migasj** [comment]
Lol thanks. I'll take a look at adding those in the next week.
